project:
  name: churn-prediction-mlops
  version: "1.0.0"
  owner: Heaven

api:
  host: "0.0.0.0"
  port: 8000
  cors_origins: ["*"]

mongodb:
  database: mlops_pipeline
  collections:
    predictions: predictions
    experiments: experiments
    users: users
    logs: logs

mlflow:
  tracking_uri: "sqlite:///mlflow.db"
  experiment_name: churn_prediction_experiments
  registered_model_name: churn_prediction_model

monitoring:
  prometheus_port: 9090
  grafana_port: 3000
